services:
- type: web
  name: aconelhamento-api
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  envVars:
    - key: SECRET_KEY
      generateValue: true
    - key: PORT
      value: 5000
  plan: free