services:
- type: web
  name: aconselhamento-api
  runtime: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
  envVars:
    - key: SECRET_KEY
      generateValue: true
  plan: free